default: &default
  :verbose: true
  :queues:
    - urgent
    - default
    - low
    - mailers

development:
  <<: *default
  :concurrency: 5
  :namespace: va_dev

test:
  <<: *default
  :namespace: va_tst

production:
  <<: *default
  :verbose: false
  :concurrency: 20
  :namespace: va_prod
  :pidfile: /var/www/apps/ved_akadem_students/shared/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
